package com.skallahaze.musiccapsule

import android.os.SystemClock

data class VisualBeatSnapshot(
    val pulse: Float = 0f,
    val bpm: Float = 0f,
    val confidence: Float = 0f,
    val sequence: Long = 0L,
    val predicted: Boolean = false,
    val updatedAt: Long = 0L,
)

/**
 * UI-only rhythm state generated by the 144 Hz renderer.
 *
 * The audio service remains the source of FFT data. This lightweight layer
 * remembers recent beat intervals, fills occasional missed kicks and exposes a
 * held beat meter so a short onset is still visible in the settings screen.
 */
object VisualBeatRuntime {
    private val lock = Any()
    private var state = VisualBeatSnapshot()

    fun snapshot(): VisualBeatSnapshot = synchronized(lock) { state }

    fun publish(
        pulse: Float,
        bpm: Float,
        confidence: Float,
        sequence: Long,
        predicted: Boolean,
    ) = synchronized(lock) {
        state = VisualBeatSnapshot(
            pulse = pulse.coerceIn(0f, 1f),
            bpm = bpm.coerceIn(0f, 240f),
            confidence = confidence.coerceIn(0f, 1f),
            sequence = sequence,
            predicted = predicted,
            updatedAt = SystemClock.elapsedRealtime(),
        )
    }

    fun clear() = synchronized(lock) {
        state = VisualBeatSnapshot()
    }
}
